################################################################################
#
# lineapple3
#
################################################################################

LINAPPLE3_VERSION = f19dd5832038b322e43727d1d4ff2ff6c666e414
LINAPPLE3_SITE = $(call gitlab,recalbox,packages/standalone/linapple-new,$(LINAPPLE3_VERSION))
LINAPPLE3_LICENSE = GPL2
LINAPPLE3_LICENSE_FILES = COPYING

LINAPPLE3_DEPENDENCIES = sdl2 sdl2_image sdl2_ttf libcurl zlib libzip

LINAPPLE3_CONF_OPTS += -DCMAKE_C_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LINAPPLE3_CONF_OPTS += -DCMAKE_C_ARCHIVE_FINISH=true
LINAPPLE3_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_CREATE="<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>"
LINAPPLE3_CONF_OPTS += -DCMAKE_CXX_ARCHIVE_FINISH=true
LINAPPLE3_CONF_OPTS += -DCMAKE_AR="$(TARGET_CC)-ar"
LINAPPLE3_CONF_OPTS += -DCMAKE_C_COMPILER="$(TARGET_CC)"
LINAPPLE3_CONF_OPTS += -DCMAKE_CXX_COMPILER="$(TARGET_CXX)"
LINAPPLE3_CONF_OPTS += -DCMAKE_LINKER="$(TARGET_LD)"
LINAPPLE3_CONF_OPTS += -DCMAKE_C_FLAGS="$(TARGET_CFLAGS) $(COMPILER_COMMONS_CFLAGS_EXE)"
LINAPPLE3_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(TARGET_CXXFLAGS) $(COMPILER_COMMONS_CXXFLAGS_EXE)"
LINAPPLE3_CONF_OPTS += -DCMAKE_EXE_LINKER_FLAGS="$(TARGET_LDFLAGS) $(COMPILER_COMMONS_LDFLAGS_EXE)"

$(eval $(cmake-package))
