################################################################################
#
# FLYCAST_HANDHELD
#
################################################################################

# Commit of 17/05/2021
LIBRETRO_FLYCAST_HANDHELD_VERSION = 8e4fa54e26232d6d54d3b0adca163ae7e617b9bd
LIBRETRO_FLYCAST_HANDHELD_SITE = $(call github,libretro,flycast,$(LIBRETRO_FLYCAST_HANDHELD_VERSION))
LIBRETRO_FLYCAST_HANDHELD_LICENSE = GPL-2.0

LIBRETRO_FLYCAST_HANDHELD_DEPENDENCIES = arcade-dats

ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDXU4),y)
LIBRETRO_FLYCAST_HANDHELD_PLATFORM = odroid
LIBRETRO_FLYCAST_HANDHELD_SUPP_OPT += BOARD=ODROID-XU4 CC_AS="$(TARGET_CC)"
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_ODROIDGO2),y)
LIBRETRO_FLYCAST_HANDHELD_PLATFORM = odroid-go2
LIBRETRO_FLYCAST_HANDHELD_SUPP_OPT += CC_AS="$(TARGET_CC)" LDFLAGS=-lmali
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RG353X),y)
LIBRETRO_FLYCAST_HANDHELD_PLATFORM = arm64
LIBRETRO_FLYCAST_HANDHELD_SUPP_OPT += CC_AS="$(TARGET_CC)" LDFLAGS=-lmali
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPIZERO2LEGACY),y)
LIBRETRO_FLYCAST_HANDHELD_PLATFORM = rpi3
LIBRETRO_FLYCAST_HANDHELD_SUPP_OPT += CC_AS="$(TARGET_CC)"
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI3)$(BR2_PACKAGE_RECALBOX_TARGET_RPIZERO2),y)
LIBRETRO_FLYCAST_HANDHELD_PLATFORM = rpi3-mesa
LIBRETRO_FLYCAST_HANDHELD_SUPP_OPT += CC_AS="$(TARGET_CC)"
else ifeq ($(BR2_PACKAGE_RECALBOX_TARGET_RPI4_64),y)
LIBRETRO_FLYCAST_HANDHELD_PLATFORM = rpi4_64
LIBRETRO_FLYCAST_HANDHELD_SUPP_OPT += HAVE_LTCG=0 CC_AS="$(TARGET_CC)"
else
LIBRETRO_FLYCAST_HANDHELD_PLATFORM = $(RETROARCH_LIBRETRO_PLATFORM)
LIBRETRO_FLYCAST_HANDHELD_SUPP_OPT =
endif

LIBRETRO_FLYCAST_HANDHELD_SUPP_OPT += ARCH=$(BR2_NORMALIZED_ARCH)

ifeq ($(BR2_PACKAGE_RECALBOX_HAS_LIBGLES),y)
LIBRETRO_FLYCAST_HANDHELD_SUPP_OPT += FORCE_GLES=1
LIBRETRO_FLYCAST_HANDHELD_DEPENDENCIES += libgles
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
LIBRETRO_FLYCAST_HANDHELD_DEPENDENCIES += libgl
endif

LIBRETRO_FLYCAST_HANDHELD_MAKE_ARGS = platform="$(LIBRETRO_FLYCAST_HANDHELD_PLATFORM)" $(LIBRETRO_FLYCAST_HANDHELD_SUPP_OPT)

define LIBRETRO_FLYCAST_HANDHELD_BUILD_CMDS
	$(SED) "s|-O2|-O3|g" $(@D)/Makefile
	CFLAGS="$(TARGET_CFLAGS) $(COMPILER_COMMONS_CFLAGS_SO)" \
		CXXFLAGS="$(TARGET_CXXFLAGS) $(COMPILER_COMMONS_CXXFLAGS_SO)" \
		LDFLAGS="$(TARGET_LDFLAGS) $(COMPILER_COMMONS_LDFLAGS_SO) -lrt" \
		$(MAKE) CXX="$(TARGET_CXX)" CC="$(TARGET_CC)" AR="$(TARGET_AR)" -C $(@D)/ -f Makefile $(LIBRETRO_FLYCAST_HANDHELD_MAKE_ARGS)
endef

define LIBRETRO_FLYCAST_HANDHELD_INSTALL_TARGET_CMDS
	$(call InstallArcadeFiles,libretro,naomi,$(LIBRETRO_FLYCAST_HANDHELD_VERSION))
	$(call InstallArcadeFiles,libretro,naomigd,$(LIBRETRO_FLYCAST_HANDHELD_VERSION))
	$(call InstallArcadeFiles,libretro,atomiswave,$(LIBRETRO_FLYCAST_HANDHELD_VERSION))
	$(INSTALL) -D $(@D)/flycast_libretro.so \
		$(TARGET_DIR)/usr/lib/libretro/flycast_libretro.so
	mkdir -p $(TARGET_DIR)/recalbox/share_upgrade/bios/dc
endef

$(eval $(generic-package))
