/**
 * @author Nicolas TESSIER aka Asthonishia
 */
export const ARCHITECTURE = '/architecture';

export const BIOS = {
  root: '/bios',
  all: '/bios',
  export: '/bios/download',
  upload: '/bios/upload/',
};

export const CONFIGURATION = {
  audio: '/configuration/audio',
  autorun: '/configuration/autorun',
  controllers: '/configuration/controllers',
  emustation: '/configuration/emulationstation',
  global: '/configuration/global',
  hat: '/configuration/hat',
  hyperion: '/configuration/hyperion',
  kodi: '/configuration/kodi',
  music: '/configuration/music',
  patreon: 'configuration/patron',
  scraper: '/configuration/scraper',
  screenshots: '/configuration/screenshots',
  system: '/configuration/system',
  systems: {
    '3do': '/configuration/system/3do',
    '64dd': '/configuration/system/64dd',
    amiga600: '/configuration/system/amiga600',
    amiga1200: '/configuration/system/amiga1200',
    amigacd32: '/configuration/system/amigacd32',
    amigacdtv: '/configuration/system/amigacdtv',
    amstradcpc: '/configuration/system/amstradcpc',
    apple2: '/configuration/system/apple2',
    apple2gs: '/configuration/system/apple2gs',
    arduboy: '/configuration/system/arduboy',
    atari800: '/configuration/system/atari800',
    atari2600: '/configuration/system/atari2600',
    atari5200: '/configuration/system/atari5200',
    atari7800: '/configuration/system/atari7800',
    atarist: '/configuration/system/atarist',
    atomiswave: '/configuration/system/atomiswave',
    bbcmicro: '/configuration/system/bbcmicro',
    bk: '/configuration/system/bk',
    c64: '/configuration/system/c64',
    cdi: '/configuration/system/cdi',
    channelf: '/configuration/system/channelf',
    colecovision: '/configuration/system/colecovision',
    daphne: '/configuration/system/daphne',
    dos: '/configuration/system/dos',
    dragon: '/configuration/system/dragon',
    dreamcast: '/configuration/system/dreamcast',
    easyrpg: '/configuration/system/easyrpg',
    fbneo: '/configuration/system/fbneo',
    fds: '/configuration/system/fds',
    gamecube: '/configuration/system/gamecube',
    gamegear: '/configuration/system/gamegear',
    gb: '/configuration/system/gb',
    gba: '/configuration/system/gba',
    gbc: '/configuration/system/gbc',
    gw: '/configuration/system/gw',
    gx4000: '/configuration/system/gx4000',
    intellivision: '/configuration/system/intellivision',
    jaguar: '/configuration/system/jaguar',
    lowresnx: '/configuration/system/lowresnx',
    lutro: '/configuration/system/lutro',
    lynx: '/configuration/system/lynx',
    macintosh: '/configuration/system/macintosh',
    mame: '/configuration/system/mame',
    mastersystem: '/configuration/system/mastersystem',
    megadrive: '/configuration/system/megadrive',
    megaduck: '/configuration/system/megaduck',
    model3: '/configuration/system/model3',
    moonlight: '/configuration/system/moonlight',
    msx1: '/configuration/system/msx1',
    msx2: '/configuration/system/msx2',
    msxturbor: '/configuration/system/msxturbor',
    multivision: '/configuration/system/multivision',
    n64: '/configuration/system/n64',
    naomi: '/configuration/system/naomi',
    naomi2: '/configuration/system/naomi2',
    naomigd: '/configuration/system/naomigd',
    nds: '/configuration/system/nds',
    neogeo: '/configuration/system/neogeo',
    neogeocd: '/configuration/system/neogeocd',
    nes: '/configuration/system/nes',
    ngp: '/configuration/system/ngp',
    ngpc: '/configuration/system/ngpc',
    o2em: '/configuration/system/o2em',
    openbor: '/configuration/system/openbor',
    oricatmos: '/configuration/system/oricatmos',
    palm: '/configuration/system/palm',
    pc88: '/configuration/system/pc88',
    pc98: '/configuration/system/pc98',
    pcengine: '/configuration/system/pcengine',
    pcenginecd: '/configuration/system/pcenginecd',
    pcfx: '/configuration/system/pcfx',
    pcv2: '/configuration/system/pcv2',
    pico: '/configuration/system/pico',
    pico8: '/configuration/system/pico8',
    pokemini: '/configuration/system/pokemini',
    ports: '/configuration/system/ports',
    psp: '/configuration/system/psp',
    ps2: '/configuration/system/ps2',
    psx: '/configuration/system/psx',
    samcoupe: '/configuration/system/samcoupe',
    satellaview: '/configuration/system/satellaview',
    saturn: '/configuration/system/saturn',
    scummvm: '/configuration/system/scummvm',
    scv: '/configuration/system/scv',
    sega32x: '/configuration/system/sega32x',
    segacd: '/configuration/system/segacd',
    sg1000: '/configuration/system/sg1000',
    snes: '/configuration/system/snes',
    solarus: '/configuration/system/solarus',
    spectravideo: '/configuration/system/spectravideo',
    sufami: '/configuration/system/sufami',
    supergrafx: '/configuration/system/supergrafx',
    supervision: '/configuration/system/supervision',
    thomson: '/configuration/system/thomson',
    ti994a: '/configuration/system/ti994a',
    tic80: '/configuration/system/tic80',
    trs80coco: '/configuration/system/trs80coco',
    uzebox: '/configuration/system/uzebox',
    vectrex: '/configuration/system/vectrex',
    vg5000: '/configuration/system/vg5000',
    vic20: '/configuration/system/vic20',
    videopacplus: '/configuration/system/videopacplus',
    virtualboy: '/configuration/system/virtualboy',
    wasm4: '/configuration/system/wasm4',
    wii: '/configuration/system/wii',
    wswan: '/configuration/system/wswan',
    wswanc: '/configuration/system/wswanc',
    x1: '/configuration/system/x1',
    x68000: '/configuration/system/x68000',
    zmachine: '/configuration/system/zmachine',
    zx81: '/configuration/system/zx81',
    zxspectrum: '/configuration/system/zxspectrum',
  },
  tate: '/configuration/tate',
  updates: '/configuration/updates',
  wifi: '/configuration/wifi',
  wifi2: '/configuration/wifi2',
  wifi3: '/configuration/wifi3',
};

export const SYSTEM = {
  es: {
    start: '/system/frontend/start',
    stop: '/system/frontend/stop',
    restart: '/system/frontend/restart',
  },
  reboot: '/system/reboot',
  shutdown: '/system/shutdown',
  supportArchive: '/system/supportarchive',
};

export const MEDIA = {
  root: '/media',
  all: '/media',
  get: '/media/screenshot/',
  delete: '/media/',
  takeScreenshot: '/media/takescreenshot',
};

export const MONITORING = {
  cpuInfo: '/monitoring/cpuinfo',
  storageInfo: '/monitoring/storageinfo',
};

export const ROMS = {
  root: '/roms',
  all: '/roms',
};

export const SYSTEMS = {
  root: '/systems',
  all: '/systems',
  system: {
    '3do': '/3do/roms',
    '64dd': '/64dd/roms',
    amiga600: '/amiga600/roms',
    amiga1200: '/amiga1200/roms',
    amigacd32: '/amigacd32/roms',
    amigacdtv: '/amigacdtv/roms',
    amstradcpc: '/amstradcpc/roms',
    apple2: '/apple2/roms',
    apple2gs: '/apple2gs/roms',
    arduboy: '/arduboy/roms',
    atari800: '/atari800/roms',
    atari2600: '/atari2600/roms',
    atari5200: '/atari5200/roms',
    atari7800: '/atari7800/roms',
    atarist: '/atarist/roms',
    atomiswave: '/atomiswave/roms',
    bbcmicro: '/bbcmicro/roms',
    bk: '/bk/roms',
    c64: '/c64/roms',
    cdi: '/cdi/roms',
    channelf: '/channelf/roms',
    colecovision: '/colecovision/roms',
    daphne: '/daphne/roms',
    dos: '/dos/roms',
    dragon: '/dragon/roms',
    dreamcast: '/dreamcast/roms',
    easyrpg: '/easyrpg/roms',
    fbneo: '/fbneo/roms',
    fds: '/fds/roms',
    gamecube: '/gamecube/roms',
    gamegear: '/gamegear/roms',
    gb: '/gb/roms',
    gba: '/gba/roms',
    gbc: '/gbc/roms',
    gw: '/gw/roms',
    gx4000: '/gx4000/roms',
    intellivision: '/intellivision/roms',
    jaguar: '/jaguar/roms',
    lowresnx: '/lowresnx/roms',
    lutro: '/lutro/roms',
    lynx: '/lynx/roms',
    macintosh: '/macintosh/roms',
    mame: '/mame/roms',
    mastersystem: '/mastersystem/roms',
    megadrive: '/megadrive/roms',
    megaduck: '/megaduck/roms',
    model3: '/model3/roms',
    moonlight: '/moonlight/roms',
    msx1: '/msx1/roms',
    msx2: '/msx2/roms',
    msxturbor: '/msxturbor/roms',
    multivision: '/multivision/roms',
    n64: '/n64/roms',
    naomi: '/naomi/roms',
    naomi2: '/naomi2/roms',
    naomigd: '/naomigd/roms',
    nds: '/nds/roms',
    neogeo: '/neogeo/roms',
    neogeocd: '/neogeocd/roms',
    nes: '/nes/roms',
    ngp: '/ngp/roms',
    ngpc: '/ngpc/roms',
    o2em: '/o2em/roms',
    openbor: '/openbor/roms',
    oricatmos: '/oricatmos/roms',
    palm: '/palm/roms',
    pc88: '/pc88/roms',
    pc98: '/pc98/roms',
    pcengine: '/pcengine/roms',
    pcenginecd: '/pcenginecd/roms',
    pcfx: '/pcfx/roms',
    pcv2: '/pcv2/roms',
    pico: '/pico/roms',
    pico8: '/pico8/roms',
    pokemini: '/pokemini/roms',
    ports: '/ports/roms',
    psp: '/psp/roms',
    ps2: '/ps2/roms',
    psx: '/psx/roms',
    samcoupe: '/samcoupe/roms',
    satellaview: '/satellaview/roms',
    saturn: '/saturn/roms',
    scummvm: '/scummvm/roms',
    scv: '/scv/roms',
    sega32x: '/sega32x/roms',
    segacd: '/segacd/roms',
    sg1000: '/sg1000/roms',
    snes: '/snes/roms',
    solarus: '/solarus/roms',
    spectravideo: '/spectravideo/roms',
    sufami: '/sufami/roms',
    supergrafx: '/supergrafx/roms',
    supervision: '/supervision/roms',
    thomson: '/thomson/roms',
    ti994a: '/ti994a/roms',
    tic80: '/tic80/roms',
    trs80coco: '/trs80coco/roms',
    uzebox: '/uzebox/roms',
    vectrex: '/vectrex/roms',
    vg5000: '/vg5000/roms',
    vic20: '/vic20/roms',
    videopacplus: '/videopacplus/roms',
    virtualboy: '/virtualboy/roms',
    wasm4: '/wasm4/roms',
    wii: '/wii/roms',
    wswan: '/wswan/roms',
    wswanc: '/wswanc/roms',
    x1: '/x1/roms',
    x68000: '/x68000/roms',
    zmachine: '/zmachine/roms',
    zx81: '/zx81/roms',
    zxspectrum: '/zxspectrum/roms',
  },
};

export const TWITCH = {
  auth: 'https://id.twitch.tv/oauth2/token',
  schedule: 'https://api.twitch.tv/helix/schedule',
};

export const VERSIONS = '/versions';
