#!/bin/bash

# This file runs migration scripts ONCE
## Migration type will save the migration stamp will be save in BOOT or SHARE
## Migrations will NOT be done on fresh install

# Run this script on startup only
if [[ $1 != "start" ]]; then
  exit 0
fi

# Useful global variables
INIT_SCRIPT=$(basename "$0")

##########################
###     Migrations     ###
##########################

recallog -s "${INIT_SCRIPT}" -t "MIGRATION" "Running MIGRATIONS..."
BOOT_TYPE="boot"
SHARE_TYPE="share"

declare -A MIGRATION_FILES=(
    [$BOOT_TYPE]="/boot/.system-migrations"
    [$SHARE_TYPE]="/recalbox/share/system/.system-migrations"
)

function migrationDone {
    local MIGRATIONTYPE="${1}"
    local MIGRATION="${2}"
    if [[ "${MIGRATIONTYPE}" == "${BOOT_TYPE}" ]];then
        mount -o remount,rw /boot
        echo "${MIGRATION}" >> "${MIGRATION_FILES[${BOOT_TYPE}]}"
        mount -o remount,ro /boot
    elif [[ "${MIGRATIONTYPE}" == "${SHARE_TYPE}" ]];then
        echo "${MIGRATION}" >> "${MIGRATION_FILES[${SHARE_TYPE}]}"
    fi
}

function shouldMigrate {
    local MIGRATIONTYPE="${1}"
    local MIGRATION="${2}"
    # The file does not exists, we should create it
    if [ -n "${MIGRATION_FILES[${MIGRATIONTYPE}]}" ] && [ ! -f "${MIGRATION_FILES[${MIGRATIONTYPE}]}" ]; then
        recallog -s "${INIT_SCRIPT}" -t "MIGRATION" "Creating migration stamp file ${MIGRATION_FILES[${MIGRATIONTYPE}]}"
        migrationDone "${MIGRATIONTYPE}" "#Migrations"
    fi
    # On first install we should not migrate
    # so we save the migration as done and don't let the migration happen
    if [ -f "/tmp/.first-install" ]; then
        recallog -s "${INIT_SCRIPT}" -t "MIGRATION" "First install, ignoring ${MIGRATION}"
        migrationDone "${MIGRATIONTYPE}" "${MIGRATION}"
        return 1
    fi

    ! grep -q "${MIGRATION}" "${MIGRATION_FILES[${MIGRATIONTYPE}]}"
}

function runMigrations {
    if shouldMigrate "${BOOT_TYPE}" "9.1-hdmi-hotplug"; then
        # HDMI hotplug options should be removed from recalbox-user-config.txt for all
        # See https://gitlab.com/recalbox/recalbox/-/merge_requests/2514
        source /recalbox/scripts/recalbox-utils.sh
        if [[ $(getArchName) =~ rpi* ]] && [ -f "/boot/recalbox-user-config.txt" ];then
            recallog -s "${INIT_SCRIPT}" -t "MIGRATION" "Running migration 9.1-hdmi-hotplug"
            mount -o remount,rw /boot
            sed -i "s/hdmi_force_hotplug=./hdmi_force_hotplug=0/g" "/boot/recalbox-user-config.txt"
            mount -o remount,ro /boot
            migrationDone "${BOOT_TYPE}" "9.1-hdmi-hotplug"
            reboot
            return
        else
            migrationDone "${BOOT_TYPE}" "9.1-hdmi-hotplug"
        fi
    fi
    if shouldMigrate "${SHARE_TYPE}" "9.1-model3-save"; then
        # Model 3 have invalid save directory
        source /recalbox/scripts/recalbox-utils.sh
        if [[ "$(getArchName)" = "x86_64" ]];then
            recallog -s "${INIT_SCRIPT}" -t "MIGRATION" "Running 9.1-model3-save"
            rm -rf "/recalbox/share/saves/model3/"
            migrationDone "${SHARE_TYPE}" "9.1-model3-save"
            return
        else
            migrationDone "${SHARE_TYPE}" "9.1-model3-save"
        fi
    fi
    if shouldMigrate "${SHARE_TYPE}" "9.2-move-bios"; then
        # Move bios into specific directories
        recallog -s "${INIT_SCRIPT}" -t "MIGRATION" "Running migration 9.2-move-bios"
        mv "/recalbox/share/bios/5200.ROM" "/recalbox/share/bios/atari5200" 2>/dev/null
        mv "/recalbox/share/bios/ATARIBAS.ROM" "/recalbox/share/bios/atari800" 2>/dev/null
        mv "/recalbox/share/bios/ATARIOSA.ROM" "/recalbox/share/bios/atari800" 2>/dev/null
        mv "/recalbox/share/bios/ATARIOSB.ROM" "/recalbox/share/bios/atari800" 2>/dev/null
        mv "/recalbox/share/bios/ATARIXL.ROM" "/recalbox/share/bios/atari800" 2>/dev/null
        mv "/recalbox/share/bios/upd7801g.s01" "/recalbox/share/bios/scv/upd7801g.s01" 2>/dev/null
        mv "/recalbox/share/bios/bios_MD.bin" "/recalbox/share/bios/megadrive" 2>/dev/null
        mv "/recalbox/share/bios/bios.gg" "/recalbox/share/bios/gamegear" 2>/dev/null
        mv "/recalbox/share/bios/bios_E.sms" "/recalbox/share/bios/mastersystem" 2>/dev/null
        mv "/recalbox/share/bios/bios_J.sms" "/recalbox/share/bios/mastersystem" 2>/dev/null
        mv "/recalbox/share/bios/bios_U.sms" "/recalbox/share/bios/mastersystem" 2>/dev/null
        mv "/recalbox/share/bios/bios_CD_E.bin" "/recalbox/share/bios/segacd" 2>/dev/null
        mv "/recalbox/share/bios/bios_CD_J.bin" "/recalbox/share/bios/segacd" 2>/dev/null
        mv "/recalbox/share/bios/bios_CD_U.bin" "/recalbox/share/bios/segacd" 2>/dev/null
        mv "/recalbox/share/bios/7800 BIOS (E).rom" "/recalbox/share/bios/atari7800" 2>/dev/null
        mv "/recalbox/share/bios/7800 BIOS (U).rom" "/recalbox/share/bios/atari7800" 2>/dev/null
        mv "/recalbox/share/bios/lynxboot.img" "/recalbox/share/bios/lynx" 2>/dev/null
        [ -d "/recalbox/share/bios/nds" ] && mkdir -p "/recalbox/share/bios/nds"
        mv "/recalbox/share/bios/bios7.bin" "/recalbox/share/bios/nds" 2>/dev/null
        mv "/recalbox/share/bios/bios9.bin" "/recalbox/share/bios/nds" 2>/dev/null
        mv "/recalbox/share/bios/firmware.bin" "/recalbox/share/bios/nds" 2>/dev/null
        [ -d "/recalbox/share/bios/saturn" ] && mkdir -p "/recalbox/share/bios/saturn"
        mv "/recalbox/share/bios/saturn_bios.bin" "/recalbox/share/bios/saturn" 2>/dev/null
        mv "/recalbox/share/bios/stvbios.zip" "/recalbox/share/bios/saturn" 2>/dev/null
        mv "/recalbox/share/bios/sega_101.bin" "/recalbox/share/bios/saturn" 2>/dev/null
        mv "/recalbox/share/bios/mpr-17933.bin" "/recalbox/share/bios/saturn" 2>/dev/null
        mv "/recalbox/share/bios/mpr-18811-mx.ic1" "/recalbox/share/bios/saturn" 2>/dev/null
        mv "/recalbox/share/bios/mpr-19367-mx.ic1" "/recalbox/share/bios/saturn" 2>/dev/null
        [ -d "/recalbox/share/bios/pcfx" ] && mkdir -p "/recalbox/share/bios/pcfx"
        mv "/recalbox/share/bios/pcfx.rom" "/recalbox/share/bios/pcfx" 2>/dev/null
        mv "/recalbox/share/bios/bootloader-dbvz.rom" "/recalbox/share/bios/palm" 2>/dev/null
        mv "/recalbox/share/bios/palmos41-en-m515.rom" "/recalbox/share/bios/palm" 2>/dev/null
        mv "/recalbox/share/bios/CARTS.SHA" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/CYRILLIC.FNT" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/DISK.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/FMPAC16.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/FMPAC.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/ITALIC.FNT" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/KANJI.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/MSX2EXT.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/MSX2PEXT.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/MSX2P.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/MSX2.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/MSXDOS2.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/MSX.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/PAINTER.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/RS232.ROM" "/recalbox/share/bios/msx" 2>/dev/null
        mv "/recalbox/share/bios/sl31253.bin" "/recalbox/share/bios/channelf" 2>/dev/null
        mv "/recalbox/share/bios/sl31254.bin" "/recalbox/share/bios/channelf" 2>/dev/null
        mv "/recalbox/share/bios/sl90025.bin" "/recalbox/share/bios/channelf" 2>/dev/null
        mv "/recalbox/share/bios/exec.bin" "/recalbox/share/bios/intellivision" 2>/dev/null
        mv "/recalbox/share/bios/grom.bin" "/recalbox/share/bios/intellivision" 2>/dev/null
        mv "/recalbox/share/bios/c52.bin" "/recalbox/share/bios/o2em" 2>/dev/null
        mv "/recalbox/share/bios/g7400.bin" "/recalbox/share/bios/o2em" 2>/dev/null
        mv "/recalbox/share/bios/jopac.bin" "/recalbox/share/bios/o2em" 2>/dev/null
        mv "/recalbox/share/bios/o2rom.bin" "/recalbox/share/bios/o2em" 2>/dev/null
        [ -d "/recalbox/share/bios/3do" ] && mkdir -p "/recalbox/share/bios/3do"
        mv "/recalbox/share/bios/panafz1.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/panafz1j.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/panafz1j-norsa.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/panafz10.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/panafz10-norsa.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/panafz10e-anvil.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/panafz10e-anvil-norsa.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/goldstar.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/sanyotry.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/3do_arcade_saot.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/panafz1-kanji.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/panafz1j-kanji.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/panafz10ja-anvil-kanji.bin" "/recalbox/share/bios/3do" 2>/dev/null
        mv "/recalbox/share/bios/bios.min" "/recalbox/share/bios/pokemini" 2>/dev/null
        mv "/recalbox/share/bios/disksys.rom" "/recalbox/share/bios/fds" 2>/dev/null
        mv "/recalbox/share/bios/gb_bios.bin" "/recalbox/share/bios/gb" 2>/dev/null
        mv "/recalbox/share/bios/dmg_boot.bin" "/recalbox/share/bios/gb" 2>/dev/null
        mv "/recalbox/share/bios/sgb_bios.bin" "/recalbox/share/bios/sgb" 2>/dev/null
        mv "/recalbox/share/bios/sgb_boot.bin" "/recalbox/share/bios/sgb" 2>/dev/null
        mv "/recalbox/share/bios/sgb2_boot.bin" "/recalbox/share/bios/sgb" 2>/dev/null
        mv "/recalbox/share/bios/SGB1.sfc" "/recalbox/share/bios/sgb" 2>/dev/null
        mv "/recalbox/share/bios/SGB2.sfc" "/recalbox/share/bios/sgb" 2>/dev/null
        mv "/recalbox/share/bios/gbc_bios.bin" "/recalbox/share/bios/gbc" 2>/dev/null
        mv "/recalbox/share/bios/cgb_boot.bin" "/recalbox/share/bios/gbc" 2>/dev/null
        mv "/recalbox/share/bios/gba_bios.bin" "/recalbox/share/bios/gba" 2>/dev/null
        mv "/recalbox/share/bios/agb_boot.bin" "/recalbox/share/bios/gba" 2>/dev/null
        [ -d "/recalbox/share/bios/satellaview" ] && mkdir -p "/recalbox/share/bios/satellaview"
        mv "/recalbox/share/bios/BS-X.bin" "/recalbox/share/bios/satellaview" 2>/dev/null
        [ -d "/recalbox/share/bios/sufami" ] && mkdir -p "/recalbox/share/bios/sufami"
        mv "/recalbox/share/bios/STBIOS.bin" "/recalbox/share/bios/sufami" 2>/dev/null
        mv "/recalbox/share/bios/gexpress.pce" "/recalbox/share/bios/pcengine" 2>/dev/null
        mv "/recalbox/share/bios/syscard1.pce" "/recalbox/share/bios/pcenginecd" 2>/dev/null
        mv "/recalbox/share/bios/syscard2.pce" "/recalbox/share/bios/pcenginecd" 2>/dev/null
        mv "/recalbox/share/bios/syscard3.pce" "/recalbox/share/bios/pcenginecd" 2>/dev/null
        rm -rf "/recalbox/share/bios/64DD_IPL.bin"
        sed -i "s|ROM_400/800_CUSTOM=/recalbox/share/bios/ATARIOSB.ROM|ROM_400/800_CUSTOM=/recalbox/share/bios/atari800/ATARIOSB.ROM|g" "/recalbox/share/system/.atari800.cfg"
        sed -i "s|ROM_5200=/recalbox/share/bios/5200.rom|ROM_5200=/recalbox/share/bios/atari5200/5200.rom|g" "/recalbox/share/system/.atari800.cfg"
        sed -i "s|ROM_BASIC_C=/recalbox/share/bios/ATARIBAS.ROM|ROM_BASIC_C=/recalbox/share/bios/atari800/ATARIBAS.ROM|g" "/recalbox/share/system/.atari800.cfg"
        sed -i "s|ROM_OS_A_PAL=/recalbox/share/bios/ATARIOSA.ROM|ROM_OS_A_PAL=/recalbox/share/bios/atari800/ATARIOSA.ROM|g" "/recalbox/share/system/.atari800.cfg"
        sed -i "s|ROM_OS_BB01R2=/recalbox/share/bios/ATARIXL.ROM|ROM_OS_BB01R2=/recalbox/share/bios/atari800/ATARIXL.ROM|g" "/recalbox/share/system/.atari800.cfg"
        migrationDone "${SHARE_TYPE}" "9.2-move-bios"
    fi
}

runMigrations