#!/usr/bin/env python
import os
from configgen.utils.recallog import recallog

ssh_file = "/recalbox/share/system/.ssh/authorized_keys"
data_file = "/boot/user-data"
network_file = "/boot/network-.con"

if os.path.isfile(data_file):
    import yaml
    import configgen.recalboxFiles as recalboxFiles
    from configgen.settings.keyValueSettings import keyValueSettings

    with open(data_file, "r") as userdata:
        userconf = yaml.safe_load(userdata)

    recalconf = keyValueSettings(recalboxFiles.recalboxConf, False)
    recalconf.loadFile(True)

    if userconf["users"][0]["ssh_authorized_keys"]:
        recallog("Configuration SSH Key")
        try:
            os.makedirs(os.path.dirname(ssh_file), exist_ok=True)
        except OSError as error:
            recallog(error)
        with open(ssh_file, "w") as keyfile:
            keyfile.write(userconf["users"][0]["ssh_authorized_keys"][0])
            keyfile.close()

    if userconf["hostname"]:
        recallog("Configuration Hostname")
        recalconf.setOption("system.hostname", userconf["hostname"])
        recalconf.safeSaveFile()
    try:
        os.remove(data_file)
    except OSError as error:
        recallog(error)

if os.path.isfile(network_file):
    recallog("Configuration WIFI")
    import yaml
    import configgen.recalboxFiles as recalboxFiles
    from configgen.settings.keyValueSettings import keyValueSettings

    with open(network_file, "r") as userdata:
        networkconf = yaml.safe_load(userdata)

    recalconf = keyValueSettings(recalboxFiles.recalboxConf, False)
    recalconf.loadFile(True)

    if networkconf["wifis"]["wlan0"]["access-points"]:
        for key, value in networkconf["wifis"]["wlan0"]["access-points"].items():
            ssid = key
            password = value["password"]

        recalconf.setOption("wifi.enabled", "1")
        recalconf.setOption("wifi.ssid", ssid)
        recalconf.setOption("wifi.key", password)
        recalconf.safeSaveFile()
    try:
        os.remove(network_file)
    except OSError as error:
        recallog(error)

recallog("Not found postconfig data")
