#!/usr/bin/env python
import os
from configgen.utils.recallog import recallog

ssh_file = "/recalbox/share/system/.ssh/authorized_keys"
data_file = "/boot/user-data"
network_files = ["/boot/network-.con", "/boot/network-config"]
shadow_file = "/run/recalbox.shadow"

if os.path.isfile(data_file):
    import yaml
    import configgen.recalboxFiles as recalboxFiles
    from configgen.settings.keyValueSettings import keyValueSettings

    with open(data_file, "r") as userdata:
        userconf = yaml.safe_load(userdata)

    recalconf = keyValueSettings(recalboxFiles.recalboxConf, False)
    recalconf.loadFile(True)

    if "users" in userconf and len(userconf["users"]) > 0:
        if "ssh_authorized_keys" in userconf["users"][0]:
            recallog("Configuration SSH Key")
            try:
                os.makedirs(os.path.dirname(ssh_file), exist_ok=True)
            except OSError as error:
                recallog(error)
            with open(ssh_file, "w") as keyfile:
                keyfile.write(userconf["users"][0]["ssh_authorized_keys"][0])
                keyfile.close()
        if "passwd" in userconf["users"][0]:
            password = userconf["users"][0]["passwd"]
            recallog("Configuration Root password")
            text_shadow = "root:{}:19949::::::".format(password)
            if not os.path.isfile(shadow_file):
                f = open(shadow_file, "a")
                f.close
            try:
                f = open(shadow_file, "w")
                f.write(text_shadow)
                f.close
            except IOError:
                recallog("While trying to perform write password, an error occurred.")
            recalconf.setOption("system.default_password", 0)
            recalconf.safeSaveFile()

    if "hostname" in userconf:
        recallog("Configuration Hostname")
        recalconf.setOption("system.hostname", userconf["hostname"])
        recalconf.safeSaveFile()
    try:
        os.remove(data_file)
    except OSError as error:
        recallog(error)

for network_file in network_files:
    if os.path.isfile(network_file):
        recallog("Configuration WIFI")
        import yaml
        import configgen.recalboxFiles as recalboxFiles
        import subprocess
        from configgen.settings.keyValueSettings import keyValueSettings

        with open(network_file, "r") as userdata:
            networkconf = yaml.safe_load(userdata)

        recalconf = keyValueSettings(recalboxFiles.recalboxConf, False)
        recalconf.loadFile(True)

        if networkconf["wifis"]["wlan0"]["access-points"]:
            for key, value in networkconf["wifis"]["wlan0"]["access-points"].items():
                ssid = key
                password = value["password"]

            recalconf.setOption("wifi.enabled", "1")
            recalconf.setOption("wifi.ssid", ssid)
            recalconf.setOption("wifi.key", password)
            recalconf.safeSaveFile()
            subprocess.run(["/etc/init.d/S09wifi", "start"])
        try:
            os.remove(network_file)
        except OSError as error:
            recallog(error)

recallog("Not found postconfig data")
