image: python:3.9-slim
      
stages:
  - build

build:
  stage: build
  script: 
    - echo "Installing dependencies"
    - pip install pygame pytest pytest-cov pytest-subprocess pytest-mock pytest-lazy-fixture
    - echo "Running unittests" 
    - export PYTHONPATH=$PYTHONPATH:$(pwd) && pytest --cov=configgen
    - echo "Building configgen" 
    - python setup.py install
