//
// Created by bkg2k on 17/12/23.
//
#pragma once

#include <utils/storage/EnumBitArray.h>

enum class ThemePropertyName
{
  Alignment = 0,
  Animations,
  BackgroundColor,
  Color,
  ColorTop,
  ColorBottom,
  ColorLeft,
  ColorRight,
  ColorTopLeft,
  ColorTopRight,
  ColorBottomLeft,
  ColorBottomRight,
  DefaultTransition,
  Delay,
  Disabled,
  Display,
  FadePath,
  FilledPath,
  FontPath,
  FontSize,
  FontColor,
  ForceUppercase,
  Height,
  HorizontalMargin,
  IconA,
  IconAdvanced,
  IconArcade,
  IconB,
  IconColor,
  IconControllers,
  IconDownload,
  IconFastShutdown,
  IconGames,
  IconKodi,
  IconL,
  IconLeftRight,
  IconLicense,
  IconNetwork,
  IconQuit,
  IconR,
  IconRecalboxRGBDual,
  IconRestart,
  IconScraper,
  IconSelect,
  IconShutdown,
  IconSound,
  IconStart,
  IconSystem,
  IconTate,
  IconUI,
  IconUpDown,
  IconUpDownLeftRight,
  IconUpdates,
  IconX,
  IconY,
  LineSpacing,
  Link,
  LogoAlignment,
  LogoRotation,
  LogoRotationOrigin,
  LogoScale,
  LogoSize,
  Loops,
  MaxLogoCount,
  MaxSize,
  Origin,
  Path,
  PathOff,
  PathOn,
  Pos,
  PrimaryColor,
  Reflection,
  Rotation,
  RotationOrigin,
  ScrollSound,
  SecondaryColor,
  SelectedColor,
  SelectorColor,
  SelectorHeight,
  SelectorImagePath,
  SelectorImageTile,
  SelectorOffsetY,
  SeparatorColor,
  Size,
  Text,
  TextColor,
  Tile,
  Type,
  UnfilledPath,
  ZIndex,
  Count__, //!< Special count element
};

typedef EnumBitArray<ThemePropertyName, ThemePropertyName::Count__> ThemePropertyNameBits;