//
// Created by bkg2k on 16/12/23.
//

#include "ThemeSupport.h"

HashSet<String>& ThemeSupport::SupportedViews()
{
  static HashSet<String> sSupportedViews;
  if (sSupportedViews.empty())
    for(const String& value : String("system,basic,detailed,menu,gameclip").Split(','))
      sSupportedViews.insert(value);
  return sSupportedViews;
}

HashSet<String>& ThemeSupport::SupportedFeatures()
{
  static HashSet<String> sSupportedFeatures;
  if (sSupportedFeatures.empty())
    for(const String& value : String("carousel,z-index").Split(','))
      sSupportedFeatures.insert(value);
  return sSupportedFeatures;
}

HashMap< String, HashMap<String, ThemeSupport::ElementProperty> >& ThemeSupport::ElementMap()
{
  static HashMap< String, HashMap<String, ThemeSupport::ElementProperty> > sElementMap =
    {
      { "image",
        {
          { "pos", ElementProperty::NormalizedPair },
          { "size", ElementProperty::NormalizedPair },
          { "maxSize", ElementProperty::NormalizedPair },
          { "origin", ElementProperty::NormalizedPair },
          { "rotation", ElementProperty::Float },
          { "rotationOrigin", ElementProperty::NormalizedPair },
          { "path", ElementProperty::Path },
          { "tile", ElementProperty::Boolean },
          { "color", ElementProperty::Color },
          { "zIndex", ElementProperty::Float },
          { "disabled", ElementProperty::Boolean },
        },
      },
      { "box",
        {
          { "pos", ElementProperty::NormalizedPair },
          { "size", ElementProperty::NormalizedPair },
          { "origin", ElementProperty::NormalizedPair },
          { "rotation", ElementProperty::Float },
          { "rotationOrigin", ElementProperty::NormalizedPair },
          { "color", ElementProperty::Color },
          { "zIndex", ElementProperty::Float },
          { "disabled", ElementProperty::Boolean },
        },
      },
      { "video",
        {
          { "pos", ElementProperty::NormalizedPair },
          { "size", ElementProperty::NormalizedPair },
          { "maxSize", ElementProperty::NormalizedPair },
          { "origin", ElementProperty::NormalizedPair },
          { "rotation", ElementProperty::Float },
          { "rotationOrigin", ElementProperty::NormalizedPair },
          { "path", ElementProperty::Path },
          { "zIndex", ElementProperty::Float },
          { "disabled", ElementProperty::Boolean },
          { "animations", ElementProperty::String },
          { "loops", ElementProperty::Float },
          { "delay", ElementProperty::Float },
        },
      },
      { "text",
        {
          { "pos", ElementProperty::NormalizedPair },
          { "size", ElementProperty::NormalizedPair },
          { "origin", ElementProperty::NormalizedPair },
          { "rotation", ElementProperty::Float },
          { "rotationOrigin", ElementProperty::NormalizedPair },
          { "text", ElementProperty::String },
          { "path", ElementProperty::Path },
          { "backgroundColor", ElementProperty::Color },
          { "fontPath", ElementProperty::Path },
          { "fontSize", ElementProperty::Float },
          { "color", ElementProperty::Color },
          { "alignment", ElementProperty::String },
          { "forceUppercase", ElementProperty::Boolean },
          { "lineSpacing", ElementProperty::Float },
          { "value", ElementProperty::String },
          { "zIndex", ElementProperty::Float },
          { "disabled", ElementProperty::Boolean },
        },
      },
      { "scrolltext",
        {
          { "pos", ElementProperty::NormalizedPair },
          { "size", ElementProperty::NormalizedPair },
          { "origin", ElementProperty::NormalizedPair },
          { "rotation", ElementProperty::Float },
          { "rotationOrigin", ElementProperty::NormalizedPair },
          { "text", ElementProperty::String },
          { "path", ElementProperty::Path },
          { "backgroundColor", ElementProperty::Color },
          { "fontPath", ElementProperty::Path },
          { "fontSize", ElementProperty::Float },
          { "color", ElementProperty::Color },
          { "alignment", ElementProperty::String },
          { "forceUppercase", ElementProperty::Boolean },
          { "value", ElementProperty::String },
          { "zIndex", ElementProperty::Float },
          { "disabled", ElementProperty::Boolean },
        },
      },
      { "textlist",
        {
          { "pos", ElementProperty::NormalizedPair },
          { "size", ElementProperty::NormalizedPair },
          { "origin", ElementProperty::NormalizedPair },
          { "selectorHeight", ElementProperty::Float },
          { "selectorOffsetY", ElementProperty::Float },
          { "selectorColor", ElementProperty::Color },
          { "selectorImagePath", ElementProperty::Path },
          { "selectorImageTile", ElementProperty::Boolean },
          { "selectedColor", ElementProperty::Color },
          { "primaryColor", ElementProperty::Color },
          { "secondaryColor", ElementProperty::Color },
          { "fontPath", ElementProperty::Path },
          { "fontSize", ElementProperty::Float },
          { "scrollSound", ElementProperty::Path },
          { "alignment", ElementProperty::String },
          { "horizontalMargin", ElementProperty::Float },
          { "forceUppercase", ElementProperty::Boolean },
          { "lineSpacing", ElementProperty::Float },
          { "zIndex", ElementProperty::Float },
        },
      },
      { "container",
        {
          { "pos", ElementProperty::NormalizedPair },
          { "size", ElementProperty::NormalizedPair },
          { "origin", ElementProperty::NormalizedPair },
          { "zIndex", ElementProperty::Float },
          { "disabled", ElementProperty::Boolean },
        },
      },
      { "ninepatch",
        {
          { "pos", ElementProperty::NormalizedPair },
          { "size", ElementProperty::NormalizedPair },
          { "path", ElementProperty::Path },
          { "zIndex", ElementProperty::Float },
          { "disabled", ElementProperty::Boolean },
        },
      },
      { "datetime",
        {
          { "pos", ElementProperty::NormalizedPair },
          { "size", ElementProperty::NormalizedPair },
          { "origin", ElementProperty::NormalizedPair },
          { "color", ElementProperty::Color },
          { "fontPath", ElementProperty::Path },
          { "fontSize", ElementProperty::Float },
          { "alignment", ElementProperty::String },
          { "forceUppercase", ElementProperty::Boolean },
          { "zIndex", ElementProperty::Float },
          { "disabled", ElementProperty::Boolean },
          { "display", ElementProperty::String },
        },
      },
      { "rating",
        {
          { "pos", ElementProperty::NormalizedPair },
          { "size", ElementProperty::NormalizedPair },
          { "origin", ElementProperty::NormalizedPair },
          { "rotation", ElementProperty::Float },
          { "rotationOrigin", ElementProperty::NormalizedPair },
          { "filledPath", ElementProperty::Path },
          { "unfilledPath", ElementProperty::Path },
          { "zIndex", ElementProperty::Float },
          { "disabled", ElementProperty::Boolean },
        },
      },
      { "sound",
        {
          { "path", ElementProperty::Path },
        },
      },
      { "helpsystem",
        {
          { "pos", ElementProperty::NormalizedPair },
          { "textColor", ElementProperty::Color },
          { "iconColor", ElementProperty::Color },
          { "fontPath", ElementProperty::Path },
          { "fontSize", ElementProperty::Float },
          { "iconUpDown", ElementProperty::Path },
          { "iconLeftRight", ElementProperty::Path },
          { "iconUpDownLeftRight", ElementProperty::Path },
          { "iconA", ElementProperty::Path },
          { "iconB", ElementProperty::Path },
          { "iconX", ElementProperty::Path },
          { "iconY", ElementProperty::Path },
          { "iconL", ElementProperty::Path },
          { "iconR", ElementProperty::Path },
          { "iconStart", ElementProperty::Path },
          { "iconSelect", ElementProperty::Path },
        },
      },
      { "carousel",
        {
          { "type", ElementProperty::String },
          { "size", ElementProperty::NormalizedPair },
          { "pos", ElementProperty::NormalizedPair },
          { "origin", ElementProperty::NormalizedPair },
          { "color", ElementProperty::Color },
          { "logoScale", ElementProperty::Float },
          { "logoRotation", ElementProperty::Float },
          { "logoRotationOrigin", ElementProperty::NormalizedPair },
          { "logoSize", ElementProperty::NormalizedPair },
          { "logoAlignment", ElementProperty::String },
          { "maxLogoCount", ElementProperty::Float },
          { "defaultTransition", ElementProperty::String },
          { "zIndex", ElementProperty::Float },
        },
      },
      { "menuBackground",
        {
          { "color", ElementProperty::Color },
          { "path", ElementProperty::Path },
          { "fadePath", ElementProperty::Path },
        },
      },
      { "menuIcons",
        {
          { "iconKodi", ElementProperty::Path },
          { "iconSystem", ElementProperty::Path },
          { "iconSystem", ElementProperty::Path },
          { "iconUpdates", ElementProperty::Path },
          { "iconControllers", ElementProperty::Path },
          { "iconGames", ElementProperty::Path },
          { "iconUI", ElementProperty::Path },
          { "iconSound", ElementProperty::Path },
          { "iconNetwork", ElementProperty::Path },
          { "iconScraper", ElementProperty::Path },
          { "iconAdvanced", ElementProperty::Path },
          { "iconQuit", ElementProperty::Path },
          { "iconRestart", ElementProperty::Path },
          { "iconShutdown", ElementProperty::Path },
          { "iconFastShutdown", ElementProperty::Path },
          { "iconLicense", ElementProperty::Path },
          { "iconRecalboxRGBDual", ElementProperty::Path },
          { "iconTate", ElementProperty::Path },
          { "iconArcade", ElementProperty::Path },
          { "iconDownload", ElementProperty::Path },
        },
      },
      { "menuSwitch",
        {
          { "pathOn", ElementProperty::Path },
          { "pathOff", ElementProperty::Path },
        },
      },
      { "menuSlider",
        {
          { "path", ElementProperty::Path },
        },
      },
      { "menuButton",
        {
          { "path", ElementProperty::Path },
          { "filledPath", ElementProperty::Path },
        },
      },
      { "menuText",
        {
          { "fontPath", ElementProperty::Path },
          { "fontSize", ElementProperty::Float },
          { "color", ElementProperty::Color },
          { "separatorColor", ElementProperty::Color },
          { "selectedColor", ElementProperty::Color },
          { "selectorColor", ElementProperty::Color },
        },
      },
      { "menuTextSmall",
        {
          { "fontPath", ElementProperty::Path },
          { "fontSize", ElementProperty::Float },
          { "color", ElementProperty::Color },
          { "selectedColor", ElementProperty::Color },
          { "selectorColor", ElementProperty::Color },
        },
      },
      { "menuSize",
        {
          { "height", ElementProperty::Float },
        },
      }
    };
  return sElementMap;
}

